version: "3.9"
services:
  raitiovaunu_app:
    image: nginx:alpine
    container_name: "raitiovaunu_webserver"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raitiovaunu-website.rule=Host(`raitiovaunu.spionsatellit.com`)"
      - "traefik.http.routers.fiverr-autocompletion.tls.domains[0].main=raitiovaunu.spionsatellit.com"
      - "traefik.http.routers.raitiovaunu-website.entrypoints=websecure"
      - "traefik.http.routers.raitiovaunu-website.tls=true"
      - "traefik.http.routers.raitiovaunu-website.tls.certresolver=myresolver"
      - "traefik.http.routers.raitiovaunu-website.tls.options=raitiovaunu-website@file"
      - "traefik.http.middlewares.raitiovaunu-website-compression.compress=true"
      - "traefik.http.routers.raitiovaunu-website.middlewares=raitiovaunu-website-compression"
    networks:
      - traefik-public
    volumes:
      - "./web/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./web/dist:/usr/share/nginx/html:ro"

  raitiovaunu_api:
    container_name: "raitiovaunu_api"
    build:
      context: .
      dockerfile: api/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raitiovaunu-api.rule=Host(`api.raitiovaunu.spionsatellit.com`)"
      - "traefik.http.routers.fiverr-autocompletion.tls.domains[0].main=api.raitiovaunu.spionsatellit.com"
      - "traefik.http.routers.raitiovaunu-api.entrypoints=websecure"
      - "traefik.http.routers.raitiovaunu-api.tls=true"
      - "traefik.http.routers.raitiovaunu-api.tls.certresolver=myresolver"
      - "traefik.http.routers.raitiovaunu-api.tls.options=raitiovaunu-api@file"
      - "traefik.http.middlewares.raitiovaunu-api-compression.compress=true"
      - "traefik.http.routers.raitiovaunu-api.middlewares=raitiovaunu-api-compression"
    user: node
    restart: always
    ports:
      - 8080:8080
    networks:
      - traefik-public
    command: "npm start"

networks:
  traefik-public:
    external: true